django_social/django_social/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("posts.urls")),
    path("", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    # path("user/", include("accounts.urls")),
]

# Manages Media URLs
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_social/posts/urls.py
from django.urls import path, include
from .views import (
    PostListView,
    PostDetailView,
    PostUpdateView,
    PostDeleteView,
    PostCreateView,
    like_post,
    CommentCreateView,
    CommentDeleteView,
)

urlpatterns = [
    path("", PostListView.as_view(), name="home"),
    path("post/<str:author>/<int:pk>", PostDetailView.as_view(), name="post_detail"),
    path("post/<str:author>/<int:pk>/edit", PostUpdateView.as_view(), name="post_edit"),
    path(
        "post/<str:author>/<int:pk>/delete",
        PostDeleteView.as_view(),
        name="post_delete",
    ),
    path(
        "post/new",
        PostCreateView.as_view(),
        name="post_create",
    ),
    path("like/<int:pk>/", like_post, name="like_post"),
    ##comment
    path("comment/create/", CommentCreateView.as_view(), name="comment_create"),
    path(
        "comment/<str:author>/<int:pk>/delete",
        CommentDeleteView.as_view(),
        name="comment_delete",
    ),
]

django_social/posts/models.py
from django.db import models
from django.urls import reverse
from django_quill.fields import QuillField
from accounts.models import CustomUser


class Post(models.Model):
    author = models.ForeignKey(
        CustomUser,
        on_delete=models.CASCADE,
    )
    body = QuillField(blank=False, null=False)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    likes = models.ManyToManyField(CustomUser, blank=True, related_name="likes")

    @property
    def total_likes(self):
        return self.likes.count()

    def __str__(self):
        return str(self.author) + "_" + str(self.pk)

    def get_absolute_url(self):
        return reverse("post_detail", args=[self.author, self.pk])

    class Meta:
        db_table = "posts_post"
        ordering = ["-create_date"]


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment = models.CharField(max_length=200, blank=False, null=False)
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

    def __str__(self):
        return self.comment

    def get_absolute_url(self):
        return reverse("article_list")

django_social/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Django Social{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    {% block quill %}
    {% endblock quill %}
</head>

<body>
    <div id="splash-screen">
        <!--  splash screen content -->
        <img src="{% static 'img/logo.png' %}" class="d-inline-block img-fluid" width="150px" height="80px">
    </div>

    <div id="content" style="display: none;">

        <nav class="navbar navbar-light navbar-expand-sm border-bottom">
            <div class="container-xl">
                <a href="{% url 'home' %}" class="navbar-brand">
                    <img src="{% static 'img/logo.png' %}" class="d-inline-block img-fluid" width="150px" height="80px">
                </a>
                <!-- button for mobile nav -->
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#main-nav"
                    aria-controls="main-nav" aria-expanded="false" aria-label="Toggle navigation" id="navbar-toggler">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse justify-content-end align-center" id="main-nav">
                    <ul class="navbar-nav">
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <div class="dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                                    data-bs-toggle="dropdown" aria-expanded="false"><i
                                        class="bi bi-person-fill h4"></i></a>
                                <ul class="dropdown-menu w-25" aria-labelledby="dropdownMenuLink">
                                    <li><a class="dropdown-item"
                                            href="{% url 'user_profile' request.user.pk %}">Profile</a></li>
                                    <li><a class="dropdown-item" href="{% url 'user_list' %}">Follow/Unfollow</a></li>
                                    <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>

                                </ul>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " href="{% url 'post_create' %}"><i
                                    class="bi bi-patch-plus-fill h4"></i></a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>

        <main>
            <div class="container">
                {% block content %}
                {% endblock content %}
            </div>
        </main>

        <footer class="footer mt-5 px-4 pt-2">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-4">
                        <img src={% static "img/logo.png" %} class="d-inline-block img-fluid d-block mx-auto"
                            width="150px" height="80px">
                        <p class="text-center mb-2">©2023 Django Social</p>
                    </div>
                </div>
            </div>
        </footer>
    </div>

    <script src="{% static 'js/splash.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
        crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    {% block scripts %}
    {% endblock scripts %}
</body>

</html>

django_social/templates/comment.html
{% load crispy_forms_tags %}

<div id="form_widget-{{post.pk}}" class="mt-2 p-2 card-comments border border-1 rounded-3 " style="display: none;">
    {% for comment in post.comment_set.all %}
    <div class="container">
        <div class="row align-items-center">
            <div class="col-11">
                <a href="{% url 'user_profile' comment.author.pk %}"><span class="">@{{ comment.author }}</span></a>
                <span class="text-muted">{{ comment }}</span>
            </div>

            {% if comment.author == request.user %}
            <div class="col-1 ml-auto">
                <a href="{% url 'comment_delete' comment.author comment.pk %}" class="btn"><i
                        class="bi bi-trash3-fill"></i></a>
            </div>
            {% endif %}
        </div>
    </div>
    {% endfor %}

    <div class="container">
        <form class="row mt-2" action="{% url 'comment_create' %}" method="post">
            <div class="col-11 align-items-center">
                {% csrf_token %}
                {{ form_comment.comment|as_crispy_field }}
            </div>
            <div class="col-1 ml-1">
                <input type="hidden" name="post_id" value="{{ post.pk }}">
                <button class="btn" type="submit"><i class="bi bi-send"></i></button>
            </div>
        </form>
    </div>
</div>

django_social/templates/comment_delete.html
{% extends "base.html" %}
{% block content %}
<div class="container col-lg-8 border-3 border rounded-3 p-3">
    <h1>Delete</h1>
    <form action="" method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete the comment?</p>
        <button class="btn btn-danger ml-2" type="submit">Confirm</button>
    </form>
</div>
{% endblock content %}

django_social/templates/home.html
{% extends "base.html" %}
{% load static %}

{% block quill %}
{{ form.media }}
{% endblock quill %}

{% block content %}
{% for post in post_list %}

{% include 'post_base.html' %}

{% endfor %}

{% if not post_list %}
<p class="text-muted text-center"><i class="bi bi-cup-hot-fill"></i> Oops... Your feed is empty, <a
        href="{% url 'user_list' %}">start following some
        users to see
        their posts.</a></p>
{% endif %}

{% endblock content %}

{% block scripts %}
<script src="{% static 'js/likes.js' %}"></script>
<script src="{% static 'js/comments.js' %}"></script>
{% endblock scripts %}

django_social/templates/post_base.html
<article class="mb-3 post">
    <div class="row justify-content-center align-items-center">
        <div class="card border border-2  rounded-3" style="width: 40rem;">
            <div class="card-body"><img src="{{post.author.avatar.url}}" alt="user" class="img-fluid rounded-5 me-1"
                    style="max-width: 50px;">
                <h1 class="card-title h6" style="display: inline;"><a class="text-decoration-none"
                        href="{% url 'user_profile' post.author.pk %}">@{{post.author}}</a></h1>
                {% if user.pk == post.author.pk or request.resolver_match.url_name != 'post_detail' %}
                <button class="btn ms-2" data-bs-toggle="modal" data-bs-target="#modal_{{post.pk}}"><i
                        class="bi bi-three-dots"></i></button>
                {% endif %}
                {% if user.last_login < post.create_date %} <span class="badge bg-secondary">New</span> {% endif %}
                    <p class="card-subtitle text-muted mt-1">
                        {% if post.create_date|date:'Y-m-d H:i:s' != post.update_date|date:'Y-m-d H:i:s' %}
                        {{ post.create_date }} (edited)
                        {% else %}
                        {{ post.create_date }}
                        {% endif %}
                    </p>
                    <p class="card-text mx-4 mt-2">{{post.body.html|safe}}</p>

                    <!-- Like Button -->
                    <button class="btn card-link like-button {% if request.user in post.likes.all %}liked{% endif %}"
                        id="like-button-{{ post.pk }}" onclick="handleLike('{{ post.pk }}')">
                        <i class=" bi bi-heart-fill"></i></button>
                    <span id="like-count-{{ post.pk }}">{{ post.total_likes }}</span>

                    <!-- Comment Button -->
                    <button id="comment-toggler-{{ post.pk }}" class="btn card-link"
                        onclick="toggle_form_widget('comment-toggler-{{ post.pk }}', 'form_widget-{{ post.pk }}')"><i
                            class="bi bi-chat-left-text-fill"></i></button>

                    {% include 'comment.html' %}


            </div>
        </div>
    </div>
</article>

<div class="modal fade" id="modal_{{post.pk}}" tabindex="-1" aria-labelledby="post-modal-label" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body text-center">
                {% if request.resolver_match.url_name != 'post_detail' %}
                <a href="{% url 'post_detail' post.author post.pk %}">Open Post</a>
                <hr>
                {% endif %}
                {% if user.pk == post.author.pk %}
                <a href="{{post.get_absolute_url}}/edit">Edit</a>
                <hr>
                <a href="{{post.get_absolute_url}}/delete">Delete</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>

django_social/templates/post_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block quill %}
{{ form.media }}
{% endblock quill %}

{% block content %}
<div class="container col-lg-8 border-3 border rounded-3 p-3">
    <h1 class="h3">New Post</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-primary ml-2" type="submit">Create Post</button>
    </form>
</div>

{% endblock content %}

django_social/templates/post_delete.html
{% extends "base.html" %}
{% block content %}
<div class="container col-lg-8 border-3 border rounded-3 p-3">
    <h1 class="h3">Delete</h1>
    <form action="" method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete the post?</p>
        <button class="btn btn-danger ml-2" type="submit">Confirm</button>
    </form>
</div>
{% endblock content %}

django_social/templates/post_detail.html
{% extends "base.html" %}
{% load static %}

{% block quill %}
{{ form.media }}
{% endblock quill %}

{% block content %}

{% include 'post_base.html' %}

{% endblock content %}

{% block scripts %}
<script src="{% static 'js/likes.js' %}"></script>
<script src="{% static 'js/comments.js' %}"></script>
{% endblock scripts %}

django_social/templates/post_edit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block quill %}
{{ form.media }}
{% endblock quill %}

{% block content %}

<div class="container col-lg-8 border-3 border rounded-3 p-3">
    <h1 class="h3">Edit Post</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-primary ml-2" type="submit">Update</button>
    </form>
</div>
{% endblock content %}

django_social/templates/user_change.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}



<div class="container col-lg-8 border-3 border rounded-3 p-3">
    <h1 class="h3">Edit Profile</h1>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-success ml-2" type="submit">Edit Profile</button>
    </form>

    <p class="mt-3"><a class="" href="{% url 'password_reset' %}">Do you want to change
            your password?</a></p>
</div>



{% endblock content %}

django_social/templates/user_detail.html
{% extends 'base.html' %}

{% load static %}

{% block quill %}
{{ form.media }}
{% endblock quill %}

{% block content %}


<section class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col col-md-9 col-lg-7 col-xl-5">
            <div class="card border border-2 rounded-4">
                <div class="card-body p-4">
                    <div class="d-flex text-black">
                        <div class="flex-shrink-0">
                            <img src="{{object.avatar.url}}" alt="Generic placeholder image" class="img-fluid rounded-4"
                                style="width: 180px;">
                        </div>
                        <div class="flex-grow-1 ms-3">
                            <div>
                                <span class="mb-1 h5">{{object.first_name}} {{object.last_name}} </span>
                                <span>
                                    {% if request.user.pk == object.pk %}
                                    <a href="{% url 'user_change' %}"><i class="bi bi-pencil-fill"></i></a>
                                    {% endif %}
                                </span>
                            </div>
                            <p class="mb-2 pb-1 badge bg-primary" style="color: #efefef;">@{{object.username}}</p>
                            <div class="d-md-flex  justify-content-evenly rounded-3 p-2 mb-2"
                                style="background-color: #efefef;">
                                <div>
                                    <p class="small text-muted mb-1">Posts</p>
                                    <p class="mb-0">{{post_count}}</p>
                                </div>
                                <div class="px-md-3">
                                    <p class="small text-muted mb-1">Followers</p>
                                    <p class="mb-0">{{followers_count}}</p>
                                </div>
                                <div>
                                    <p class="small text-muted mb-1">Following</p>
                                    <p class="mb-0">{{following_count}}</p>
                                </div>
                            </div>
                            <div class="d-flex pt-1">
                                {% if request.user.pk != object.pk %}
                                <!-- <button type="button" class="btn btn-outline-primary me-1 flex-grow-1">Chat</button> -->
                                <!-- <button type="button" class="btn btn-primary flex-grow-1">Follow</button> -->

                                <form method="post" action="{% url 'follow_toggle' object.pk %}">
                                    {% csrf_token %}
                                    <!-- redirect to this page after POST handled -->
                                    <input type="hidden" name="next_page" value="{{ request.path }}">
                                    <button type="submit" class="btn btn-primary flex-grow-1">
                                        {% if is_following %}
                                        Unfollow
                                        <input type="hidden" name="action" value="unfollow">
                                        {% else %}
                                        Follow
                                        <input type="hidden" name="action" value="follow">
                                        {% endif %}
                                    </button>
                                </form>




                                {% endif %}
                            </div>
                        </div>

                    </div>
                    {% if object.bio %}<p class="mt-3 mb-0 text-muted">{{object.bio}}</p>{% endif %}
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Display User Post List -->

{% for post in posts %}

{% include 'post_base.html' %}

{% endfor %}

{% endblock content %}

{% block scripts %}
<script src="{% static 'js/likes.js' %}"></script>
<script src="{% static 'js/comments.js' %}"></script>
{% endblock scripts %}

django_social/templates/user_list.html
{% extends "base.html" %}

{% block content %}
<h1 class="">All Users</h1>
<p class=" mb-4">Follow your favourite users to see their posts in your feed.</p>

{% for user in users %}
<div class="col-lg-8 py-2">

    <div class="row justify-content-start border border-3 rounded-4 py-2">
        <div class="col-lg-1 col-2">
            <img src="{{user.avatar.url}}" alt="user" class="img-fluid rounded-5" style="max-width: 50px;">
        </div>
        <div class="col-lg-9 col-6 justify-items-start">
            <h6 class="h6"><a href="{% url 'user_profile' user.pk %}" class="profile-link">@{{user.username}}</a></h6>
            {% if user.bio %}<p class="text-muted fs-6 m-0" style="word-wrap: break-word;">{{user.bio}}</p>{% endif %}
        </div>
        <div class="col-lg-2 col-2">
            {% if user.pk not in following %}
            <form action="{% url 'follow_toggle' user.pk %}" method="POST">
                {% csrf_token %}
                <!-- used to redirect to this page after POST handled -->
                <input type="hidden" name="next_page" value="{{ request.path }}">
                <button class="btn btn-primary" type="submit" name="action" value="follow">Follow</button>
            </form>
            {% else %}
            <form action="{% url 'follow_toggle' user.pk %}" method="POST">
                {% csrf_token %}
                <!-- used to redirect to this page after POST handled -->
                <input type="hidden" name="next_page" value="{{ request.path }}">
                <button class="btn btn-primary" type="submit" name="action" value="unfollow">Unfollow</button>
            </form>
            {% endif %}
        </div>
    </div>

</div>
{% endfor %}

{% endblock %}